# ENV
NUMBER_EPISODES = 100000    # agent training
EPISODES_WITH_HUMAN = 1     # games with human

# Robot type
TOM = 0
NO_TOM = 1
DECEPTION = 2
EXTERNAL_DECEPTION = 3
SUPERFICIAL_DECEPTION = 4
HIDDEN_DECEPTION = 5

# Constraint for first flip suggestion
CLICKS_UNTIL_MATCH_THRESHOLD_WITH_PAIR = 4
CLICKS_UNTIL_MATCH_THRESHOLD_WITHOUT_PAIR = 9

# Action
SUGGEST_NONE = 0
SUGGEST_ROW_COLUMN = 1
SUGGEST_CARD = 2

# Reward for suggestions
REWARD_SUGGEST_NONE = 10
REWARD_SUGGEST_RC =  0.2
REWARD_SUGGEST_CARD = 0.025

# Constants for game state
BEGIN_STATE = 3 
MIDDLE_STATE = 2.5 
END_STATE = 0.8

# Constant for attempts
LOW_STATE = 2
MEDIUM_STATE = 4
HIGH_STATE = 6

# Q-table states
INIT_STATE = 0

NO_HELP_BEG_F_CORRECT = 1
NO_HELP_BEG_F_WRONG_LOW = 2
NO_HELP_BEG_F_WRONG_MEDIUM = 3
NO_HELP_BEG_F_WRONG_HIGH = 4

NO_HELP_MID_F_CORRECT = 5
NO_HELP_MID_F_WRONG_LOW = 6
NO_HELP_MID_F_WRONG_MEDIUM = 7
NO_HELP_MID_F_WRONG_HIGH = 8

NO_HELP_END_F_CORRECT = 9
NO_HELP_END_F_WRONG_LOW = 10
NO_HELP_END_F_WRONG_MEDIUM = 11
NO_HELP_END_F_WRONG_HIGH = 12

SUGG_ROW_BEG_F_CORRECT = 13
SUGG_ROW_BEG_F_WRONG_LOW = 14
SUGG_ROW_BEG_F_WRONG_MEDIUM = 15
SUGG_ROW_BEG_F_WRONG_HIGH = 16

SUGG_ROW_MID_F_CORRECT = 17
SUGG_ROW_MID_F_WRONG_LOW = 18
SUGG_ROW_MID_F_WRONG_MEDIUM = 19
SUGG_ROW_MID_F_WRONG_HIGH = 20

SUGG_ROW_END_F_CORRECT = 21
SUGG_ROW_END_F_WRONG_LOW = 22
SUGG_ROW_END_F_WRONG_MEDIUM = 23
SUGG_ROW_END_F_WRONG_HIGH = 24

SUGG_CARD_BEG_F_CORRECT = 25
SUGG_CARD_BEG_F_WRONG_LOW = 26
SUGG_CARD_BEG_F_WRONG_MEDIUM = 27
SUGG_CARD_BEG_F_WRONG_HIGH = 28

SUGG_CARD_MID_F_CORRECT = 29
SUGG_CARD_MID_F_WRONG_LOW = 30
SUGG_CARD_MID_F_WRONG_MEDIUM = 31
SUGG_CARD_MID_F_WRONG_HIGH = 32

SUGG_CARD_END_F_CORRECT = 33
SUGG_CARD_END_F_WRONG_LOW = 34
SUGG_CARD_END_F_WRONG_MEDIUM = 35
SUGG_CARD_END_F_WRONG_HIGH = 36

NO_HELP_BEG_S_CORRECT = 37
NO_HELP_BEG_S_WRONG_LOW = 38
NO_HELP_BEG_S_WRONG_MEDIUM = 39
NO_HELP_BEG_S_WRONG_HIGH = 40

NO_HELP_MID_S_CORRECT = 41
NO_HELP_MID_S_WRONG_LOW = 42
NO_HELP_MID_S_WRONG_MEDIUM = 43
NO_HELP_MID_S_WRONG_HIGH = 44

NO_HELP_END_S_CORRECT = 45
NO_HELP_END_S_WRONG_LOW = 46
NO_HELP_END_S_WRONG_MEDIUM = 47
NO_HELP_END_S_WRONG_HIGH = 48

SUGG_ROW_BEG_S_CORRECT = 49
SUGG_ROW_BEG_S_WRONG_LOW = 50
SUGG_ROW_BEG_S_WRONG_MEDIUM = 51
SUGG_ROW_BEG_S_WRONG_HIGH = 52

SUGG_ROW_MID_S_CORRECT = 53
SUGG_ROW_MID_S_WRONG_LOW = 54
SUGG_ROW_MID_S_WRONG_MEDIUM = 55
SUGG_ROW_MID_S_WRONG_HIGH = 56

SUGG_ROW_END_S_CORRECT = 57
SUGG_ROW_END_S_WRONG_LOW = 58
SUGG_ROW_END_S_WRONG_MEDIUM = 59
SUGG_ROW_END_S_WRONG_HIGH = 60

SUGG_CARD_BEG_S_CORRECT = 61
SUGG_CARD_BEG_S_WRONG_LOW = 62
SUGG_CARD_BEG_S_WRONG_MEDIUM = 63
SUGG_CARD_BEG_S_WRONG_HIGH = 64

SUGG_CARD_MID_S_CORRECT = 65
SUGG_CARD_MID_S_WRONG_LOW = 66
SUGG_CARD_MID_S_WRONG_MEDIUM = 67
SUGG_CARD_MID_S_WRONG_HIGH = 68

SUGG_CARD_END_S_CORRECT = 69
SUGG_CARD_END_S_WRONG_LOW = 70
SUGG_CARD_END_S_WRONG_MEDIUM = 71
SUGG_CARD_END_S_WRONG_HIGH = 72   